server:
    port: 8761

eureka:
    instance:
        appname: registry
        hostname: localhost
        prefer-ip-address: true
    server:
        enable-self-preservation: true
    client:
        registerWithEureka: false
        fetchRegistry: false
spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Desktop/config
        bootstrap: true
        prefix: /config
