server:
    port: 8761

eureka:
    instance:
        appname: registry
        hostname: localhost
        prefer-ip-address: true
    server:
        enable-self-preservation: true
    client:
        registerWithEureka: false
        fetchRegistry: false

spring:
    application:
        name: jhipster-registry
    profiles:
        active: native
    cloud:
        config:
            server:
                #git:
                #    uri: ${HOME}/config
                native:
                    search-locations: file:./central-config
                prefix: /config
