# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
    port: 8761

eureka:
    instance:
        appname: registry
        hostname: localhost
        prefer-ip-address: true
    server:
        enable-self-preservation: true
    client:
        registerWithEureka: false
        fetchRegistry: false

spring:
    application:
        name: jhipster-registry

